# Demo root admin password.
#
# Set ONCE in terraform.tfvars (gitignored) and reused across every
# destroy/apply cycle — so reviewers don't get a new password every time
# you tear down and rebuild the cluster.
#
# If you omit `admin_password` from terraform.tfvars, Terraform falls back
# to a random one generated by the resource below — but that random value
# regenerates on each destroy, so reviewers would need a fresh credential
# after every cycle. Pick a value in tfvars to avoid that.
#
# Either way, the password ends up only in:
#   1. terraform.tfstate (local, gitignored)
#   2. The woms-secrets K8s Secret (created imperatively from this output)
# It is NEVER committed to git.

variable "admin_password" {
  description = "Demo admin password. Set in terraform.tfvars to keep stable across destroy/apply; leave empty to auto-generate (changes each cycle)."
  type        = string
  sensitive   = true
  default     = ""
}

resource "random_password" "admin_password" {
  count   = var.admin_password == "" ? 1 : 0
  length  = 20
  special = false
}

locals {
  effective_admin_password = var.admin_password != "" ? var.admin_password : random_password.admin_password[0].result
}
