# Demo root admin credentials.
#
# The password is generated by Terraform (no human ever types it) and ends
# up in two places only:
#   1. terraform.tfstate (local, gitignored)
#   2. The woms-secrets K8s Secret (created imperatively from this output)
#
# It is NEVER committed to git. Reviewers / graders need the password? Run:
#
#   terraform -chdir=infra output -raw admin_password
#
# The seed Job (`k8s/25-seed-admin-job.yaml`) reads the password from the
# Secret at runtime, so the YAML file is safe to commit.

resource "random_password" "admin_password" {
  length  = 20
  special = false # avoid characters that need escaping in PowerShell / shells
}
