# PostgreSQL on RDS — single-AZ db.t3.micro, free-tier-eligible for new
# accounts (750 hr/month for 12 months). Otherwise ~$12/month.
#
# Lives in the private subnets — no public IP, so only resources inside the
# VPC (EKS pods, a bastion if we ever add one) can reach it.
#
# The password is generated by Terraform and never typed by a human. It ends
# up in `terraform.tfstate` (local, gitignored) and is exposed as a sensitive
# output for Phase 3 to plumb into a K8s Secret.

resource "random_password" "db_password" {
  length  = 24
  special = false # avoid characters that need escaping in connection strings
}

# Tells RDS which subnets it may launch the DB instance in.
resource "aws_db_subnet_group" "main" {
  name       = "${var.project}-${var.environment}-db"
  subnet_ids = module.vpc.private_subnets

  tags = {
    Name = "${var.project}-${var.environment}-db-subnet-group"
  }
}

# Security group: allow Postgres traffic (5432/tcp) from anything inside the
# VPC. In a tighter prod setup you'd narrow this to the EKS node SG only —
# fine for a demo, simplifies debugging.
resource "aws_security_group" "rds" {
  name        = "${var.project}-${var.environment}-rds"
  description = "Allow PostgreSQL access from inside the VPC"
  vpc_id      = module.vpc.vpc_id

  ingress {
    from_port   = 5432
    to_port     = 5432
    protocol    = "tcp"
    cidr_blocks = [module.vpc.vpc_cidr_block]
    description = "PostgreSQL from VPC"
  }

  # Egress is open by default in raw aws_security_group resources only when
  # nothing is specified, so add an explicit allow-all egress for clarity.
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow all outbound"
  }
}

resource "aws_db_instance" "main" {
  identifier = "${var.project}-${var.environment}-postgres"

  engine         = "postgres"
  engine_version = "15"
  instance_class = "db.t3.micro"

  allocated_storage     = 20
  max_allocated_storage = 30
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db_password.result

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.rds.id]

  publicly_accessible = false
  multi_az            = false

  # Demo defaults: no backups, no final snapshot on destroy, no deletion
  # protection — so `terraform destroy` actually works without manual fuss.
  backup_retention_period = 0
  skip_final_snapshot     = true
  deletion_protection     = false

  performance_insights_enabled = false

  # Apply DB engine + parameter changes immediately rather than during the
  # next maintenance window. OK for dev; in prod you'd schedule them.
  apply_immediately = true
}
